<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tenantry.Core\Tenantry.Core.csproj" />
    <ProjectReference Include="..\..\src\Tenantry.AspNetCore\Tenantry.AspNetCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\Conformance.cs" Link="Shared\Conformance.cs" />
  </ItemGroup>

</Project>
